services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - '27017'
  api:
    build: .
    container_name: api
    ports:
      - '80:8000'
    environment:
      PORT: 8000
      MONGODB_URL: mongodb://root:root@db:27017/
      NODE_ENV: development
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db