version: '3.9'
services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - '27017'
