version: '3.9'
services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    container_name: api
    depends_on:
      - db
    environment:
      MONGODB_URL: mongodb://root:root@db:27017 # in a production environment this won't be exposed
      PORT: 8000
    env_file:
      - ./JWT_SECRET.txt # in a production environment, this won't be exposed

  db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - '27017'
